# Default initial positions for robot's ros2_control fake system

initial_positions:
  robot_finger_joint1: 0.0
  robot_finger_joint2: 0.0
  Tip_Gripper_Servo_Joint: 0.0
  Tip_Gripper_Idol_Joint: 0.0
  robot_joint1: 0.0
  robot_joint2: 0.0
  robot_joint3: 0.0
  robot_joint4: 0.0
  robot_joint5: 0.0
  robot_joint6: 0.0