controller_names:
  - robot_controller

robot_controller:
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_joint1
      - robot_joint2
      - robot_joint3
      - robot_joint4
      - robot_joint5
      - robot_joint6
      - robot_finger_joint1
      - robot_finger_joint2
      - Tip_Gripper_Servo_Joint
      - Tip_Gripper_Idol_Joint
      - position
